import React from 'react';
import {
  Shield,
  ShieldCheck,
  ShieldAlert,
  Radar,
  Cpu,
  Lock,
  Eye,
  Zap,
  Activity,
  Database,
  Server,
  Cloud,
  Network,
  Brain,
  Bell,
  Users,
  Terminal,
  FileText,
  Check,
  ArrowRight,
  Phone,
  ChevronDown,
  ChevronRight,
  ChevronsDown,
  Search,
  RefreshCw,
  CheckCircle2,
  Globe,
  Radio,
  Layers,
  Sparkles,
  Award
} from 'lucide-react';

const ICON_MAP = {
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  radar: Radar,
  cpu: Cpu,
  lock: Lock,
  eye: Eye,
  zap: Zap,
  activity: Activity,
  database: Database,
  server: Server,
  cloud: Cloud,
  network: Network,
  brain: Brain,
  bell: Bell,
  users: Users,
  terminal: Terminal,
  fileText: FileText,
  check: Check,
  arrowRight: ArrowRight,
  phone: Phone,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsDown: ChevronsDown,
  search: Search,
  refresh: RefreshCw,
  checkCircle: CheckCircle2,
  globe: Globe,
  radio: Radio,
  layers: Layers,
  sparkles: Sparkles,
  award: Award
};

export default function Icon({ name, className = '', size = 20, color }) {
  const IconComponent = ICON_MAP[name] || Shield;
  return <IconComponent className={className} size={size} color={color} strokeWidth={1.75} />;
}
